[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/ui/language",
  "/configuration/ui/backend/locale",
  "/configuration/service/url",
  "/configuration/catalogAppUserId",
  "/configuration/mapServer/publishPoint",
  "/configuration/mapServer/url",
  "/configuration/mapServer/channel",
  "/configuration/mapServer/version",
  "/configuration/mapServer/request",
  "/configuration/active/layer",
  "/configuration/active/layer/properties/mapurlpath",
  "/configuration/active/layer/properties/url/pattern",
  "/configuration/active/layer/properties/url/pattern/params/service",
  "/configuration/active/layer/properties/url/pattern/params/layers",
  "/configuration/active/layer/properties/url/pattern/params/tiled",
  "/configuration/active/layer/properties/url/pattern/params/matrixset",
  "/configuration/active/layer/properties/url/pattern/params/style",
  "/configuration/active/layer/properties/url/pattern/params/projection",
  "/configuration/active/layer/properties/url/pattern/params/format",
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/map/mapmode2d",
  "/configuration/map/use/optimized/tile/requests",
  "/configuration/map/show/debugger/tool",
  "/configuration/map/show/active/layers/tool",
  "/configuration/map/show/geocoder/tool",
  "/configuration/logger/http/host",
  "/configuration/logger/http/port",
  "/configuration/logger/http/path",
  "/configuration/logger/level",
  "/configuration/logger/log2console",
  "/configuration/jobmanager/pollingcycleinterval",
  "/configuration/jobmanager/filterdaystimeslot",
  "/configuration/default/user/role",
  "/configuration/basemaps",
  "/configuration/default/terrain/provider/url",
  "/configuration/web/tools/url",
  "/configuration/model/viewer/route",
  "/configuration/model/viewer/token/value",
  "/configuration/running/mode/type",
  "/configuration/running/mode/autocomplete",
  "/configuration/served/entity/types",
  "/configuration/access/token/attribute/name",
  "/configuration/access/token/injection/type",
  "/configuration/access/token/token/value",
  "/configuration/raster/ingestion/files/structure",
  "/configuration/admin/password",
  "/configuration/project/version",
  "/configuration/whatsnew/url",
  "/configuration/sites/config",
  "/configuration/bff/path",
  "/configuration/selection/mode/default",
  "/configuration/show/selection/mode/switch",
  "/configuration/polygonparts/featuretypeprefix",
  "/configuration/polygonparts/densityfactor",
  "/configuration/polygonparts/geometry/errors/threshold",
  "/configuration/polygonparts/area/threshold",
  "/configuration/polygonparts/max/wfs/features",
  "/configuration/polygonParts/max/show/footprint/zoom/level",
  "/configuration/polygonparts/max/pershape",
  "/configuration/polygonparts/max/vertices",
  "/configuration/wfs/style",
  "/configuration/wfs/key/field",
  "/configuration/wfs/max/page/size",
  "/configuration/wfs/max/zoom/level",
  "/configuration/wfs/max/cache/size",
  "/configuration/geocoder/url",
  "/configuration/geocoder/callbackUrl",
  "/configuration/changesinshapefiles/timedifferencegraceminutes",
  "/configuration/changesinshapefiles/timemodifiedthresholdhours"
]
