apiVersion: v2
description: Helm chart to deploy Catalog App
name: catalog-app
version: 4.2.8
appVersion: 4.2.8
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
