apiVersion: v2
description: Helm chart to deploy Catalog App
name: catalog-app
version: 3.1.1
appVersion: 3.1.1
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
